Create 35.c
BitsPleaseMSI/BitsPlease-solutions pull request #35
Opened 2018-06-06 07:52 UTC by Animesh-Ghosh

Added solution to problem 35 on http://bitsplease.pythonanywhere.com/.
PS:- don't know how to evaluate the time complexity. Help anyone?

2018-06-06 12:04 UTC, Animesh-Ghosh commented
Execution output for Dev-C++ compiler.
![capture](https://user-images.githubusercontent.com/34956994/41037102-dde5288e-69af-11e8-82e7-c4010a7089d5.JPG)

2018-06-06 12:52 UTC, Bhupesh-V requested changes
Try to stick to the example format for input and output.

2018-06-06 13:14 UTC, Animesh-Ghosh commented
Done. Also, could you calculate the complexity of the program. Just curious. :D

2018-06-08 07:02 UTC, Bhupesh-V approved these changes

2018-06-08 07:24 UTC, merged